### ISSUE TITLE
`AmqpHeaderVal` features incomplete listing of types

### ISSUE THREAD

**Issue by changlinli** [profunktor/fs2-rabbit#211]
In particular currently, `AmqpHeaderVal` only has support for `Int`, `Long`, `String`, `Integer`, and `java.util.List[_]`. However, the underlying Java type being converted could be any one of the types here: https://github.com/rabbitmq/rabbitmq-java-client/blob/b55bd20a1a236fc2d1ea9369b579770fa0237615/src/main/java/com/rabbitmq/client/impl/ValueWriter.java#L128 

If one of those Java types is found, the library blows up with a `MatchError` that looks like the following:

```scala
scala.MatchError: true (of class java.lang.Boolean)
        at dev.profunktor.fs2rabbit.model$AmqpHeaderVal$.from(model.scala:99)
        at dev.profunktor.fs2rabbit.model$AmqpProperties$.$anonfun$from$5(model.scala:144)
        at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:30)
        at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:29)
        at scala.collection.immutable.HashMap.map(HashMap.scala:39)
        at dev.profunktor.fs2rabbit.model$AmqpProperties$.from(model.scala:143)
        at dev.profunktor.fs2rabbit.interpreter.AmqpClientEffect$$anon$1.handleDelivery(AMQPClientEffect.scala:59)
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

The library should be able to support any of those types in that Java file, otherwise it will blow up at runtime on decoding certain message headers.

**Comment by changlinli** [comment]
The full list of types in AMQP (which is abbreviated in the underlying Java library because Java doesn't support all of them) is listed at https://www.rabbitmq.com/amqp-0-9-1-errata.html#section_3

**Comment by changlinli** [comment]
I should be able to whip up a PR this in a few days, but if anyone else wants to fix it first, please be my guest :)

**Comment by changlinli** [comment]
So in the course of writing up this PR, I realized that this is also a change to clean up some of the `Any`s and mutability that show up in `AmqpHeaderVal`. I can replace the `collection.Seq[Any]` with a `List[AmqpHeaderVal]` at the cost of an extra copy from a mutable list to an immutable list and backwards-incompatibility between `Any` and `AmqpHeaderVal`.

Are those kinds of changes too invasive?

**Comment by changlinli** [comment]
Also it would be kind of nice to get some closure on #204 because otherwise I'm gonna have merge conflicts with any PR I make here. "kind of" because the merge conflicts are not huge.

**Comment by gvolpe** [comment]
> Are those kinds of changes too invasive?

Feel free to experiment there. I can't remember exactly why they are the way they are right now but I do remember they are a huge pain to work with. The underlying Java driver is pretty unsafe as well as the entire design of RabbitMQ headers. It's just terrible.

If we are going to make such changes we should probably add more tests around this to make sure we are not breaking things.

Re: #204 I'll get it merged once the CI build passes. Make sure you run the tests locally to avoid waiting for the CI :)

**Comment by changlinli** [comment]
Eh turns out the ordering of which one gets merged first doesn't matter as much as I thought it did. It's a merge conflict either way.
