### ISSUE TITLE
Can't find release 5.1.1 in maven repositories

### ISSUE THREAD

**Issue by Dichotomia** [profunktor/fs2-rabbit#931]
Hello.

The CI cannot download this release.

Best regards

**Comment by matejcerny** [comment]
@Dichotomia Hi, yes I know, I tried to fix broken publish pipeline but sadly without any success 😞 https://github.com/profunktor/fs2-rabbit/actions/runs/8038186694 Help is really welcomed! 🙏

**Comment by matejcerny** [comment]
Adding logs from the broken pipeline before the deletion:

```
[info] set current project to fs2-rabbit-root (in build file:/home/runner/work/fs2-rabbit/fs2-rabbit/)
2024-02-25 13:06:30.035Z  info [SonatypeService] sbt-sonatype version: 3.9.18  - (SonatypeService.scala:27)
2024-02-25 13:06:30.038Z  info [SonatypeService] sonatypeRepository  : https://oss.sonatype.org/service/local  - (SonatypeService.scala:28)
2024-02-25 13:06:30.038Z  info [SonatypeService] sonatypeProfileName : dev.profunktor  - (SonatypeService.scala:29)
[info] Preparing a new staging repository for [sbt-sonatype] fs2-rabbit-root 5.1.1+0-e9e83e5f+20[240](https://github.com/profunktor/fs2-rabbit/actions/runs/8038186694/job/21953822877#step:5:241)225-1306-SNAPSHOT
2024-02-25 13:06:30.039Z  info [SonatypeClient] Reading staging repository profiles...  - (SonatypeClient.scala:102)
2024-02-25 13:06:31.782Z  info [SonatypeClient] Reading staging profiles...  - (SonatypeClient.scala:116)
2024-02-25 13:06:33.834Z  info [SonatypeClient] Creating a staging repository in profile dev.profunktor with a description key: [sbt-sonatype] fs2-rabbit-root 5.1.1+0-e9e83e5f+20240225-1306-SNAPSHOT  - (SonatypeClient.scala:122)
2024-02-25 13:06:40.726Z  info [SonatypeService] No previous staging repository for [sbt-sonatype] fs2-rabbit-root 5.1.1+0-e9e83e5f+20240225-1306-SNAPSHOT was found  - (SonatypeService.scala:101)
2024-02-25 13:06:42.315Z  info [SonatypeClient] Created successfully: devprofunktor-1138  - (SonatypeClient.scala:135)
2024-02-25 13:06:42.328Z error [Sonatype] 
java.io.IOException: Supplied file /home/runner/work/fs2-rabbit/fs2-rabbit/target/sonatype-staging/5.1.1+0-e9e83e5f+20240225-1306-SNAPSHOT is a not an existing directory!
	at org.sonatype.spice.zapper.fs.AbstractDirectory.<init>(AbstractDirectory.java:32)
	at org.sonatype.spice.zapper.fs.DirectoryIOSource.<init>(DirectoryIOSource.java:68)
	at org.sonatype.spice.zapper.fs.DirectoryIOSource.<init>(DirectoryIOSource.java:59)
	at org.sonatype.spice.zapper.fs.DirectoryIOSource.<init>(DirectoryIOSource.java:50)
	at xerial.sbt.sonatype.SonatypeClient.$anonfun$uploadBundle$2(SonatypeClient.scala:292)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at wvlet.airframe.control.Retry$RetryContext.$anonfun$runInternal$1(Retry.scala:288)
	at scala.util.Try$.apply(Try.scala:213)
	at wvlet.airframe.control.Retry$RetryContext.runInternal(Retry.scala:286)
	at wvlet.airframe.control.Retry$RetryContext.run(Retry.scala:255)
	at xerial.sbt.sonatype.SonatypeClient.uploadBundle(SonatypeClient.scala:277)
	at xerial.sbt.sonatype.SonatypeService.uploadBundle(SonatypeService.scala:75)
	at xerial.sbt.Sonatype$.$anonfun$sonatypeBundleRelease$2(Sonatype.scala:181)
	at xerial.sbt.Sonatype$.withSonatypeService(Sonatype.scala:437)
	at xerial.sbt.Sonatype$.$anonfun$sonatypeBundleRelease$1(Sonatype.scala:177)
	at scala.Option.getOrElse(Option.scala:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)  - (Sonatype.scala:443)
```

**Comment by geirolz** [comment]
This happened to me some times ago, I had to login into [sonatype](https://oss.sonatype.org/#stagingRepositories) and manually delete the staging repository

**Comment by matejcerny** [comment]
@geirolz FYI @gvolpe deleted it, I also tried to create a new version, but still without any success

**Comment by matejcerny** [comment]
@geirolz My latest (desperate) try - creation of a tag on a feature branch: https://github.com/profunktor/fs2-rabbit/pull/953

**Comment by Dichotomia** [comment]
> @geirolz My latest (desperate) try - creation of a tag on a feature branch: #953

The error seems different in your test.

**Comment by matejcerny** [comment]
It really was a glitch in jfrog, I rerun the build and now the error is the same

**Comment by matejcerny** [comment]
I have downgraded every plugin since the latest working release and it still does not work 😡

**Comment by matejcerny** [comment]
If someone has time, feel free to completely remove the `sbt-ci-release` plugin. You can find an inspiration in this [repository](https://github.com/paoloboni/spray-json-derived-codecs/), there is a _Revert sbt-ci-release_ commit. This guy had the same [issue](https://github.com/sbt/sbt-ci-release/discussions/244)

**Comment by geirolz** [comment]
@matejcerny I'm  currently using `sbt-ci-release` in all my libraries and I've no problems - probably we are missing something 😔

**Comment by zawodskoj** [comment]
There's a discussion regarding the same issue - https://github.com/sbt/sbt-ci-release/issues/216

> The +20211209-1518 suffix in the name indicates that you have dirty git state when running publish in CI. This typically happens from website/documentation generation and you don't reproduce the issue locally because your $HOME/.gitignore file ignores the patterns that are marked as dirty in CI. You can fix this by adding more patterns to the .gitignore file of your codebase.

So I've tried to find offending files by replicating `sbt ci-publish` and found that 
`core/src/main/scala-2.12/dev/profunktor/fs2rabbit/javaConversion.scala`
appears unstaged after publish attempt

Worth trying to either ignore this file, or move codegen (if it is) to more appropriate place

**Comment by matejcerny** [comment]
I read it, but didn't have the secrets to try it out. Didn't realize that I can just use empty envs to run it 🤦‍♂️

**Comment by matejcerny** [comment]
Oh boy, it really works 🎉  It's the most silly issue in a long time! 😀 https://oss.sonatype.org/service/local/repositories/releases/content/dev/profunktor/fs2-rabbit_2.13/5.1.2/

Guys, thanks a lot for the cooperation a special thanks to Dmitri! 🙌

**Comment by matejcerny** [comment]
Btw the issue was that year 2023 in the copyright section was not updated to 2024 🤣

During the week, I will probably prepare another release with updated dependencies.

**Comment by Dichotomia** [comment]
Oh thank you 🎉

**Comment by geirolz** [comment]
@matejcerny My goodness! How did you find it ?

**Comment by matejcerny** [comment]
@geirolz Actually, Dmitri found it ^^

**Comment by geirolz** [comment]
Congrats to both of you guys, I would never have thought of that 🤣
I'm starting to think Sonatype has this error message for everything ahah
